### ISSUE TITLE
OMeta-Login

### ISSUE THREAD

**Issue by KlamChowder1** [JCVenterInstitute/OMeta-Public#3]
Hi, I'm trying to set up OMeta, and managed to finish the installation step and get the login page up and running on my localhost, but I can't seem to log in. I've set up the standalone.xml file to be have "localhost" where [GUID_SERVER_URL], [OMETA_SERVER_URL], and [LDAP_URL] are. Could you please advise me on how to proceed to set up an account for access?

Thanks,

Kevin

**Comment by kscgl** [comment]
Hello Kevin,

You need to update 'testuser' with your admin username on
OMETA_IFX_PROJECTS_db.sql (or from database manually if it's created
already) to be able to access OMeta on startup.

Your admin user/password will be authenticated through your LDAP because we
don't store any passwords in the OMeta database

Following values should work for default settings;

[GUID_SERVER_URL] = jdbc:mysql://localhost:3306/ifx_projects
[GUID_SERVER_USERNAME] = ifx_projects_adm
[GUID_SERVER_PASSWORD] = welcome

[OMETA_SERVER_URL] = jdbc:mysql://localhost:3306/jcvi_guid
[OMETA_SERVER_USERNAME] = guid_admin
[OMETA_SERVER_PASSWORD] = welcome

Example for LDAP url;

[LDAP_URL] = ldap://ds.example.com:389/

If you don't want to setup LDAP then you can setup Filesystem-Based
Identity Store, as described in section "4.1.2. Configure Authentication
with a Filesystem-Based Identity Store" in
http://docs.wildfly.org/15/WildFly_Elytron_Security.html.

Thanks,
Mehmet

**Comment by KlamChowder1** [comment]
By "updating 'testuser' with your admin username", do you mean an admin username created by LDAP? So I would have to have created a username and password for a LDAP localhost and then update that admin username as an "actor" to gain initial access to OMeta? Sorry, I'm pretty new to OpenLDAP and WildFly.

**Comment by kscgl** [comment]
Yes, any username created by your LDAP.

Just to be clear, 'testuser' has been granted admin privileges by default.
To be able to authenticate that user, it should exist in your LDAP. That's
why you need to update the username.

Eg; If you add a new user with username 'admin' to LDAP, you just need to
update actor_username column ('testuser' with 'admin') in actor table. Then
you can login to OMeta using your 'admin' credentials.

UPDATE actor SET actor_username = 'admin', actor_first_name = 'FIRSTNAME',
actor_last_name = 'LASTNAME', actor_email_address = 'admin@example.com'
WHERE actor_id = 1111111111124;

Thanks,
Mehmet

**Comment by KlamChowder1** [comment]
I see, and so for example, if I just created an LDAP username as "testuser", then since this already exists in the actor table, then I won't have to update testuser and can then I can use the LDAP password and "testuser" as the username to gain access?

**Comment by kscgl** [comment]
Yes, creating a new user as "testuser" in your LDAP should work without
updating the table.

Thanks,
Mehmet

**Comment by man4ish** [comment]
I am new to openldap and  created foo.example.org 
so i use  
LDAP_URL=ldap//foo.example.org:389/ but i am what should i write for company domain?
if i replace [COMPANY_DOMAIN] with example and run it 

./wildfly-10.0.0.Final/bin/standalone.sh -Djboss.server.base.dir=wildfly-10.0.0.Final/standalone-ometa

i get WFLYCTL0085: Failed to parse configuration error. 

I am not sure how to fix above issue.


Regards
